highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
  math_engine: MathJax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: "https://inexistent3rdchimera.github.io"
name: Inexistent3rdChimera # Required: will be displayed on every page's header
title: Inexistent3rdChimera # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - NEVER
  - OR NOW
description: "Isperia's personal blog, on TTRPGs, personal thoughts and other things..." # Required

disqus:
  comments: true # Global toggle on/off disqus comment
  shortname: unifreak # Required if you use disqus. Repalce with your disqus shortname here

google_analytics:
  id: "G-35QT9DQRZH" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  book_review:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"